### ISSUE TITLE
Logged object is persisted between entries

### ISSUE THREAD

**Issue by SeanEire** [sandorfr/az-bunyan#1]
Hi there! I'm currently looking into sending my node logs to Azure tables and came across your package. I have it wired up successfully but I'm noticing that when I log an object along with a message then that object is also appearing in the next log entry when it shouldn't. Take the following example:

```
logUtil.info('Log something here');
logUtil.info({SomeProp: 'Some object prop'}, 'Log something else with an object');
logUtil.info('Log something else');
```

This is producing the following log entries. Notice that the final entry was not logged with an object but it shows the previous one.

![image](https://cloud.githubusercontent.com/assets/11682030/6870874/b6ae2e8e-d496-11e4-847a-a1505d61edea.png)

I'm not sure if you're still supporting this package but thought I'd report the issue in case you are. Thanks!

**Comment by sandorfr** [comment]
Hi, Thanks for the report I'll check that asap.

-----Message d'origine-----
De : "SeanEire" notifications@github.com
Envoyé : ‎27/‎03/‎2015 16:36
À : "sandorfr/az-bunyan" az-bunyan@noreply.github.com
Objet : [az-bunyan] Logged object is persisted between entries (#1)

Hi there! I'm currently looking into sending my node logs to Azure tables and came across your package. I have it wired up successfully but I'm noticing that when I log an object along with a message then that object is also appearing in the next log entry when it shouldn't. Take the following example:
logUtil.info('Log something here');
logUtil.info({SomeProp: 'Some object prop'}, 'Log something else with an object');
logUtil.info('Log something else');
This is producing the following log entries. Notice that the final entry was not logged with an object but it shows the previous one.

I'm not sure if you're still supporting this package but thought I'd report the issue in case you are. Thanks!

**Comment by sandorfr** [comment]
So, basically I made a mistake when I added a tail call optimization to the column generator. Shame on me. I published a beta version with the hotfix (0.0.4 / npm install az-bunyan@beta).

Let me know if that works for you now.

**Comment by SeanEire** [comment]
Tried the beta version this morning and all looks good. Thanks for getting to it so quickly!

**Comment by sandorfr** [comment]
Great, I'll merge the patch and push the update soon.

**Comment by francesconero** [comment]
Sorry for reviving such an old issue, but are you still planning to merge the fix?

**Comment by sandorfr** [comment]
@francesconero yes, I'll do it soon.

**Comment by sandorfr** [comment]
Done
